---
apiVersion: v1
kind: Service
metadata:
  namespace: pet
  name: mysql-spc-service
  labels:
    app: petclinic
    tier: mysql
spec:
  selector:
    app: petclinic
    tier: mysql
  ports: 
    - port: 3306
      protocol: TCP
      targetPort: 3306