apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spc
        tier: app
    spec:
      containers:
        - name: spc-app
          image: wissenbaba/petclinic:spc-1
          env:
            - name: MYSQL_URL
             #Below is kubernetes mysql pod
              value: "jdbc:mysql://mysql-spc-service/petclinic"
             #RDS Connection:
              #value: "jdbc:mysql://172.20.112.39/petclinic:3306/petclinic"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: MYSQL_PASS
              valueFrom:
                 secretKeyRef:
                   name: mysql-credentials
                   key: password
          ports:
            - containerPort: 8080
